<?php
namespace ThunderBlog;
$success = function_exists('message') ? message('success', '', true) : null;
$fail = function_exists('message') ? message('fail', '', true) : null;
$renderGroup = static function(string $type, array $items, int $activeId): void { ?>
<section class="tb-admin__panel tb-admin__panel--padded tb-admin__design-group">
    <div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title"><?= esc(ucfirst($type)) ?> designs</h2><p class="tb-admin__section-text">Build reusable <?= esc($type) ?> content with the same block editor, then select the active design.</p></div><a class="tb-admin__button tb-admin__button--primary" href="<?= esc(ROOT . '/admin/blog/designs/create/' . $type) ?>"><i class="fa-solid fa-plus"></i> New <?= esc($type) ?></a></div>
    <form class="tb-admin__design-activate" method="post" action="<?= esc(ROOT . '/admin/blog/designs/activate') ?>"><?= csrf() ?><input type="hidden" name="design_type" value="<?= esc($type) ?>"><label class="tb-admin__field"><span class="tb-admin__label">Active <?= esc($type) ?></span><select class="tb-admin__select" name="design_id"><option value="0">Use the look's default <?= esc($type) ?></option><?php foreach($items as $item): ?><option value="<?= (int)$item->id ?>" <?= $activeId===(int)$item->id?'selected':'' ?>><?= esc($item->title) ?><?= $item->status!=='published'?' · '.ucfirst($item->status):'' ?></option><?php endforeach; ?></select></label><button class="tb-admin__button tb-admin__button--secondary" type="submit">Set active</button></form>
    <?php if (!$items): ?><div class="tb-admin__empty"><i class="fa-regular fa-object-group tb-admin__empty-icon"></i><h3 class="tb-admin__empty-title">No <?= esc($type) ?> designs yet</h3></div><?php else: ?><div class="tb-admin__design-grid"><?php foreach($items as $item): ?><article class="tb-admin__design-card <?= $activeId===(int)$item->id?'tb-admin__design-card--active':'' ?>"><div class="tb-admin__design-card-head"><span class="tb-admin__badge tb-admin__badge--<?= esc($item->status) ?>"><?= esc(ucfirst($item->status)) ?></span><?php if($activeId===(int)$item->id): ?><span class="tb-admin__active-chip"><i class="fa-solid fa-check"></i> Active</span><?php endif; ?></div><h3 class="tb-admin__design-title"><?= esc($item->title) ?></h3><p class="tb-admin__design-meta"><?= count(json_decode((string)$item->blocks_json,true) ?: []) ?> blocks · Updated <?= esc(get_date($item->updated_at)) ?></p><div class="tb-admin__actions"><a class="tb-admin__button tb-admin__button--secondary" href="<?= esc(blog_admin_edit_url($item)) ?>"><i class="fa-solid fa-pen"></i> Edit</a><form method="post" action="<?= esc(ROOT . '/admin/blog/' . (int)$item->id . '/delete') ?>" data-tb-confirm="Delete this design permanently?"><?= csrf() ?><button class="tb-admin__icon-button tb-admin__icon-button--danger" type="submit" title="Delete"><i class="fa-solid fa-trash"></i></button></form></div></article><?php endforeach; ?></div><?php endif; ?>
</section><?php }; ?>
<link rel="stylesheet" href="<?= esc(blog_look_http('assets/css/admin.css')) ?>">
<div class="tb-admin"><div class="tb-admin__header"><div class="tb-admin__heading-group"><span class="tb-admin__eyebrow">Thunder Blog</span><h1 class="tb-admin__title">Headers and footers</h1><p class="tb-admin__subtitle">Design reusable site chrome using the same block library and palettes as posts and pages.</p></div></div><?php if($success): ?><div class="tb-admin__notice tb-admin__notice--success"><?= esc($success) ?></div><?php endif; ?><?php if($fail): ?><div class="tb-admin__notice tb-admin__notice--danger"><?= esc($fail) ?></div><?php endif; ?><?php if($error): ?><div class="tb-admin__notice tb-admin__notice--danger"><?= esc($error) ?></div><?php endif; ?><?php $renderGroup('header',$headers,$active_header_id); $renderGroup('footer',$footers,$active_footer_id); ?></div>
<script src="<?= esc(blog_look_http('assets/js/admin.js')) ?>"></script>
