<?php
namespace ThunderBlog;
$success = function_exists('message') ? message('success', '', true) : null;
$fail = function_exists('message') ? message('fail', '', true) : null;
$custom = json_decode((string)($settings['custom_palette'] ?? ''), true);
$custom = is_array($custom) ? blog_validate_palette($custom) : blog_palette_presets()['indigo']['colors'];
$columnNames = array_map(static fn(array $column): string => (string)$column['name'], $user_columns);
$columnOptions = static function(string $selected, bool $optional = false) use ($user_columns): void {
    if ($optional) echo '<option value="">None / use authentication filter</option>';
    foreach ($user_columns as $column) {
        $name = (string)$column['name'];
        $label = $name . (!empty($column['type']) ? ' · ' . $column['type'] : '');
        echo '<option value="' . esc($name) . '" ' . ($selected === $name ? 'selected' : '') . '>' . esc($label) . '</option>';
    }
};
$previewAuthor = $author_preview['author'] ?? [];
?>
<link rel="stylesheet" href="<?= esc(blog_look_http('assets/css/admin.css')) ?>">
<div class="tb-admin">
<div class="tb-admin__header"><div class="tb-admin__heading-group"><span class="tb-admin__eyebrow">Thunder Blog</span><h1 class="tb-admin__title">Settings</h1><p class="tb-admin__subtitle">Configure the frontend look, shared colours, active designs and external author data.</p></div><a class="tb-admin__button tb-admin__button--secondary" href="<?= esc(ROOT . '/admin/blog') ?>">Back to posts</a></div>
<?php if($success): ?><div class="tb-admin__notice tb-admin__notice--success"><?= esc($success) ?></div><?php endif; ?><?php if($fail): ?><div class="tb-admin__notice tb-admin__notice--danger"><?= esc($fail) ?></div><?php endif; ?><?php if($error): ?><div class="tb-admin__notice tb-admin__notice--danger"><?= esc($error) ?></div><?php endif; ?>
<form class="tb-admin__settings-form" method="post" action="<?= esc(ROOT . '/admin/blog/settings') ?>" data-tb-author-mapping data-schema-api="<?= esc($schema_api_url) ?>"><?= csrf() ?>
<section class="tb-admin__panel tb-admin__panel--padded"><div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title">Appearance</h2><p class="tb-admin__section-text">Looks change page composition. Palettes feed the same named colours into the look, blocks, headers and footers.</p></div></div><div class="tb-admin__look-grid"><?php foreach($looks as $slug=>$look): ?><label class="tb-admin__look-card <?= ($settings['look']??'')===$slug?'tb-admin__look-card--active':'' ?>"><input class="tb-admin__look-radio" type="radio" name="look" value="<?= esc($slug) ?>" <?= ($settings['look']??'')===$slug?'checked':'' ?>><span class="tb-admin__look-preview"><i class="fa-regular fa-window-maximize"></i></span><strong class="tb-admin__look-name"><?= esc($look['name']??$slug) ?></strong><span class="tb-admin__look-description"><?= esc($look['description']??'') ?></span></label><?php endforeach; ?></div>
<div class="tb-admin__form-grid tb-admin__form-grid--three"><label class="tb-admin__field"><span class="tb-admin__label">Default palette</span><select class="tb-admin__select" name="palette" id="tb-settings-palette"><?php foreach($palette_presets as $key=>$preset): ?><option value="<?= esc($key) ?>" <?= ($settings['palette']??'')===$key?'selected':'' ?>><?= esc($preset['name']) ?></option><?php endforeach; ?><option value="custom" <?= ($settings['palette']??'')==='custom'?'selected':'' ?>>Custom palette</option></select></label><label class="tb-admin__field"><span class="tb-admin__label">Posts per page</span><input class="tb-admin__input" type="number" min="1" max="50" name="posts_per_page" value="<?= esc($settings['posts_per_page']??'9') ?>"></label></div>
<div class="tb-admin__section-heading tb-admin__section-heading--palette"><div><h3 class="tb-admin__section-title">Custom colour values</h3><p class="tb-admin__section-text">Used when Custom palette is selected.</p></div><button class="tb-admin__text-button" type="button" data-tb-reset-colors>Reset colours</button></div><div class="tb-admin__color-grid"><?php foreach($custom as $key=>$value): $field='color_'.str_replace('-','_',$key); ?><label class="tb-admin__color-field"><span class="tb-admin__label"><?= esc(ucwords(str_replace('-',' ',$key))) ?></span><span class="tb-admin__color-control"><input class="tb-admin__color-input" type="color" name="<?= esc($field) ?>" value="<?= esc($value) ?>" data-default="<?= esc(blog_palette_presets()['indigo']['colors'][$key]??$value) ?>"><input class="tb-admin__input tb-admin__input--color-text" type="text" value="<?= esc($value) ?>" data-tb-color-text></span></label><?php endforeach; ?></div>
<div class="tb-admin__check-grid"><label class="tb-admin__check"><input class="tb-admin__checkbox" type="checkbox" name="show_author" <?= ($settings['show_author']??'1')==='1'?'checked':'' ?>><span class="tb-admin__check-text">Show post author</span></label><label class="tb-admin__check"><input class="tb-admin__checkbox" type="checkbox" name="show_date" <?= ($settings['show_date']??'1')==='1'?'checked':'' ?>><span class="tb-admin__check-text">Show publication date</span></label><label class="tb-admin__check"><input class="tb-admin__checkbox" type="checkbox" name="show_category" <?= ($settings['show_category']??'1')==='1'?'checked':'' ?>><span class="tb-admin__check-text">Show category</span></label><label class="tb-admin__check"><input class="tb-admin__checkbox" type="checkbox" name="show_views" <?= ($settings['show_views']??'1')==='1'?'checked':'' ?>><span class="tb-admin__check-text">Show view count</span></label></div></section>

<section class="tb-admin__panel tb-admin__panel--padded"><div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title">Blog and search page text</h2><p class="tb-admin__section-text">Set the eyebrow, hero title and subtitle used on the main blog page and the routed blog search page.</p></div></div>
<div class="tb-admin__form-grid">
<label class="tb-admin__field"><span class="tb-admin__label">Blog page eyebrow</span><input class="tb-admin__input" type="text" name="blog_page_eyebrow" maxlength="120" value="<?= esc($settings['blog_page_eyebrow']??'Stories, ideas and updates') ?>"></label>
<label class="tb-admin__field"><span class="tb-admin__label">Search page eyebrow</span><input class="tb-admin__input" type="text" name="search_page_eyebrow" maxlength="120" value="<?= esc($settings['search_page_eyebrow']??'Stories, ideas and updates') ?>"></label>
<label class="tb-admin__field"><span class="tb-admin__label">Blog page title</span><input class="tb-admin__input" type="text" name="blog_page_title" maxlength="180" value="<?= esc($settings['blog_page_title']??'The Blog') ?>"></label>
<label class="tb-admin__field"><span class="tb-admin__label">Search page title</span><input class="tb-admin__input" type="text" name="search_page_title" maxlength="180" value="<?= esc($settings['search_page_title']??'Search the Blog') ?>"></label>
<label class="tb-admin__field"><span class="tb-admin__label">Blog page subtitle</span><textarea class="tb-admin__textarea" name="blog_page_subtitle" rows="4" maxlength="500"><?= esc($settings['blog_page_subtitle']??'Explore our latest articles and updates.') ?></textarea></label>
<label class="tb-admin__field"><span class="tb-admin__label">Search page subtitle</span><textarea class="tb-admin__textarea" name="search_page_subtitle" rows="4" maxlength="500"><?= esc($settings['search_page_subtitle']??'Find articles, topics and stories from the blog.') ?></textarea></label>
</div></section>

<section class="tb-admin__panel tb-admin__panel--padded"><div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title">Author data mapping</h2><p class="tb-admin__section-text">Choose an existing table, then map only columns that actually belong to it. New content stores the current session user's mapped primary-key value.</p></div></div>
<?php if(!$database_tables): ?><div class="tb-admin__notice tb-admin__notice--danger">No database tables could be read. Confirm the active database connection and permissions.</div><?php endif; ?>
<div class="tb-admin__form-grid tb-admin__form-grid--three">
<label class="tb-admin__field"><span class="tb-admin__label">Users table</span><select class="tb-admin__select" name="user_table" required data-tb-user-table><?php foreach($database_tables as $table): ?><option value="<?= esc($table) ?>" <?= ($settings['user_table']??'')===$table?'selected':'' ?>><?= esc($table) ?></option><?php endforeach; ?></select></label>
<label class="tb-admin__field"><span class="tb-admin__label">Primary key column</span><select class="tb-admin__select" name="user_primary_key" required data-tb-user-column data-selected="<?= esc($settings['user_primary_key']??'id') ?>"><?php $columnOptions((string)($settings['user_primary_key']??'id')); ?></select></label>
<label class="tb-admin__field"><span class="tb-admin__label">Display-name column</span><select class="tb-admin__select" name="user_display_column" required data-tb-user-column data-selected="<?= esc($settings['user_display_column']??'username') ?>"><?php $columnOptions((string)($settings['user_display_column']??'username')); ?></select></label>
<label class="tb-admin__field"><span class="tb-admin__label">Email column</span><select class="tb-admin__select" name="user_email_column" data-tb-user-column data-optional="1" data-selected="<?= esc($settings['user_email_column']??'email') ?>"><?php $columnOptions((string)($settings['user_email_column']??'email'),true); ?></select></label>
<label class="tb-admin__field"><span class="tb-admin__label">Avatar column</span><select class="tb-admin__select" name="user_avatar_column" data-tb-user-column data-optional="1" data-selected="<?= esc($settings['user_avatar_column']??'') ?>"><?php $columnOptions((string)($settings['user_avatar_column']??''),true); ?></select></label>
<label class="tb-admin__field"><span class="tb-admin__label">Profile slug column</span><select class="tb-admin__select" name="user_profile_column" data-tb-user-column data-optional="1" data-selected="<?= esc($settings['user_profile_column']??'username') ?>"><?php $columnOptions((string)($settings['user_profile_column']??'username'),true); ?></select></label>
</div>
<div class="tb-admin__author-preview"><div class="tb-admin__author-preview-icon"><?php if(!empty($previewAuthor['avatar'])): ?><img src="<?= esc($previewAuthor['avatar']) ?>" alt=""><?php else: ?><i class="fa-regular fa-user"></i><?php endif; ?></div><div><strong class="tb-admin__author-preview-name"><?= esc($previewAuthor['display_name']??'Unknown author') ?></strong><span class="tb-admin__author-preview-detail">Current session key: <code class="tb-admin__code"><?= esc((string)($author_preview['current_user_id']??'')) ?: 'empty' ?></code> · Table: <code class="tb-admin__code"><?= esc((string)($author_preview['table']??'')) ?></code></span><span class="tb-admin__author-preview-detail"><?= !empty($previewAuthor['email']) ? esc($previewAuthor['email']) : 'No email resolved' ?></span></div></div>
<div class="tb-admin__mapping-note"><i class="fa-solid fa-link"></i><span class="tb-admin__mapping-note-text">Posts store the external user key in <code class="tb-admin__code">thunder_blog_posts.author_id</code>. No foreign key is imposed, so this remains compatible with independent authentication plugins.</span></div></section>
<div class="tb-admin__settings-actions"><button class="tb-admin__button tb-admin__button--primary" type="submit">Save settings</button></div></form></div>
<script src="<?= esc(blog_look_http('assets/js/admin.js')) ?>"></script>
