<?php namespace ThunderBlog; ?>
<link rel="stylesheet" href="<?= esc(blog_look_http('assets/css/admin.css')) ?>">
<div class="tb-admin" data-tb-shortcode-generator>
    <div class="tb-admin__header"><div class="tb-admin__heading-group"><span class="tb-admin__eyebrow">Thunder Blog</span><h1 class="tb-admin__title">Shortcode generator</h1><p class="tb-admin__subtitle">Generate dynamic post-listing shortcodes for Shortcode blocks in pages, headers, footers or posts.</p></div><a class="tb-admin__button tb-admin__button--secondary" href="<?= esc(ROOT . '/admin/blog/pages/create') ?>"><i class="fa-regular fa-file-lines"></i> Create page</a></div>
    <div class="tb-admin__shortcode-layout">
        <section class="tb-admin__panel tb-admin__panel--padded"><div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title">Listing options</h2><p class="tb-admin__section-text">The generated code uses ThunderPHP's dotted shortcode name format.</p></div></div><div class="tb-admin__form-grid tb-admin__form-grid--three">
            <label class="tb-admin__field"><span class="tb-admin__label">Design</span><select class="tb-admin__select" data-tb-sc-layout><?php foreach($layouts as $value=>$label): ?><option value="<?= esc($value) ?>"><?= esc($label) ?></option><?php endforeach; ?></select></label>
            <label class="tb-admin__field"><span class="tb-admin__label">Ordering</span><select class="tb-admin__select" data-tb-sc-order><?php foreach($orders as $value=>$label): ?><option value="<?= esc($value) ?>"><?= esc($label) ?></option><?php endforeach; ?></select></label>
            <label class="tb-admin__field"><span class="tb-admin__label">Number of posts</span><input class="tb-admin__input" type="number" min="1" max="50" value="6" data-tb-sc-limit></label>
            <label class="tb-admin__field"><span class="tb-admin__label">Category</span><select class="tb-admin__select" data-tb-sc-category><option value="">All categories</option><?php foreach($categories as $category): ?><option value="<?= esc($category->slug) ?>"><?= esc($category->name) ?></option><?php endforeach; ?></select></label>
            <label class="tb-admin__field"><span class="tb-admin__label">Tag slug</span><input class="tb-admin__input" type="text" placeholder="optional-tag" data-tb-sc-tag></label>
        </div></section>
        <aside class="tb-admin__panel tb-admin__panel--padded tb-admin__shortcode-output"><div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title">Generated shortcode</h2><p class="tb-admin__section-text">Copy this into a Shortcode block.</p></div></div><textarea class="tb-admin__shortcode-code" rows="6" readonly data-tb-sc-output></textarea><button class="tb-admin__button tb-admin__button--primary" type="button" data-tb-sc-copy><i class="fa-regular fa-copy"></i> Copy shortcode</button><span class="tb-admin__copy-status" aria-live="polite" data-tb-sc-status></span><div class="tb-admin__mapping-note"><i class="fa-solid fa-code"></i><span class="tb-admin__mapping-note-text">Registered shortcode: <code class="tb-admin__code">thunder-blog.posts</code>. Output is rendered when the designed content is displayed.</span></div></aside>
    </div>
    <section class="tb-admin__panel tb-admin__panel--padded"><div class="tb-admin__section-heading"><div><h2 class="tb-admin__section-title">Available listing designs</h2><p class="tb-admin__section-text">Use small for sidebars, medium/grid for card sections, large for a feature feed, and list for compact horizontal rows.</p></div></div><div class="tb-admin__design-grid"><?php foreach($layouts as $value=>$label): ?><article class="tb-admin__design-card"><span class="tb-admin__active-chip"><?= esc($value) ?></span><h3 class="tb-admin__design-title"><?= esc($label) ?></h3><p class="tb-admin__design-meta">Works with every ordering mode and optional category or tag filtering.</p></article><?php endforeach; ?></div></section>
</div>
<script src="<?= esc(blog_look_http('assets/js/admin.js')) ?>"></script>
